#!/bin/sh
#qiv -x /home/derek/Dropbox/Wallpapers/sfbridge.jpg
#qiv -z /home/derek/Dropbox/Wallpapers/space.png
#qiv -y /home/derek/Dropbox/Wallpapers/hubble-deep-field.jpg
sleep 2
unity-settings-daemon &
nm-applet &
update-notifier &
#radiotray &
#indicator-cpufreq &
#gnome-sound-applet &
# batterymon &
dropbox start
#/usr/local/bin/komodo &
/usr/local/bin/subl &
/usr/bin/google-chrome &
#/usr/bin/polly &
#/usr/bin/redshift -l 36.762169:-119.798178 &
#buildnotifyapplet.py
